remove if it's equipped check
decentraland/kernel pull request #109
Opened 2021-11-18 19:54 UTC by leanmendoza

temp: add hotreloading for portable experiences

# What? 
...

# Why? 
...

2021-11-19 18:37 UTC, menduz commented on packages/entryPoints/index.ts
> +        })()
Please catch errors here and print to the stderr

2021-11-19 19:24 UTC, gonpombo8 commented on packages/unity-interface/dcl.ts
> +    ;(async () => {
is this anonymous fn necessary ?

2021-11-19 19:24 UTC, gonpombo8 commented on packages/unity-interface/dcl.ts
> +          await new Promise((resolve) => setTimeout(resolve, 100))
im pretty sure that we have a sleep fn at some place in this repo.
If now can we create it for future uses ?

2021-11-19 19:24 UTC, gonpombo8 commented on packages/unity-interface/dcl.ts
> +      if (collection.data.length > 0) {
```ts
      if (!!collection.data.length) {
```

2021-11-19 19:24 UTC, gonpombo8 commented on packages/entryPoints/index.ts
> +      loadPreviewScene({ ws: wsScene, message })
🎉

2021-11-22 18:17 UTC, gonpombo8 requested changes

2021-11-22 18:17 UTC, gonpombo8 commented on packages/shared/wearablesPortableExperience/sagas.ts
> +      let mappings: any = []
can we add some comments to that female/male crop ?
Also if the uniq thing that changes in the if/else clause its the file prop can we move it to a fn ?

```ts
const getFile = (key: string) => {
  if (femaleCrop) return key.substring(7)
  if (maleCrop) return key.subString(5)
  return key
}
const mappings = wearableContent.map(
  content => ({ file: getFile(content.file), hash: content.hash })
)
```

This way mapping will have types, and also inmutable 😄

2021-11-22 19:26 UTC, gonpombo8 approved these changes

2021-11-23 13:14 UTC, gonpombo8 approved these changes

2021-11-23 14:40 UTC, merged