[WIP/TEST] feat: notify the renderer when web3 is used
decentraland/kernel pull request #160
Opened 2022-01-09 20:01 UTC by kuruk-mm

# What? 
Fix decentraland/unity-renderer#1690

2022-01-17 20:09 UTC, leanmendoza requested changes
`this.parcelIdentity.land` can be undefined in Portable Experience (like smart wearables) even though currently the calls of web3 will fail in the `await this.assertHasPermissions([PermissionItem.USE_WEB3_API])` statement, there is no mechanism to grant web3 permissions to portable experience. I'm writing an example in the code that you can replicate it.
The PR looks good, I'd change that to avoid a crash in the future.

2022-01-17 22:54 UTC, kuruk-mm commented
Do not merge until the Unity PR is merged to master, and the rollout is live.

2022-01-17 22:55 UTC, leanmendoza submitted a review, later dismissed

2022-01-18 12:32 UTC, menduz commented on packages/shared/apis/EthereumController.ts
> +      sceneId: this.parcelIdentity.land?.sceneId || ''
@leanmendoza do we have a standardized way to get the sceneId for both PX and regular scenes?

2022-01-18 21:15 UTC, gonpombo8 commented on packages/shared/apis/EthereumController.ts
> +    await getUnityInstance().RequestWeb3ApiUse('requirePayment', {
what about `this.parcelIdentity.getSceneId()` so we avoid repeating this logic multiple times ?
Also we can add the logic for px there. @leanmendoza @kuruk-mm

2022-01-20 17:58 UTC, leanmendoza approved these changes

2022-01-20 17:58 UTC, leanmendoza approved these changes

2022-01-20 17:59 UTC, leanmendoza approved these changes

2022-01-20 18:18 UTC, gonpombo8 approved these changes

2022-01-20 18:19 UTC, gonpombo8 commented
😄

2022-01-20 18:39 UTC, menduz approved these changes

2022-01-20 22:14 UTC, pbosio approved these changes

2022-01-21 17:29 UTC, merged